FROM relaysh:core-python
COPY "./handler.py" "/"
ENTRYPOINT []
CMD ["python3", "/"]

LABEL "org.opencontainers.image.title"="Azure Alert triggered"
LABEL "org.opencontainers.image.description"="This trigger fires when an Azure Alert is triggered"